# Generated by Django 4.2.7 on 2024-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("church", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone_number",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
